services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-spring-app:latest
    ports:
      - "5051:5051"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

    develop:
      watch:
        - path: ./pom.xml
          action: rebuild

        - path: ./src
          action: rebuild

        - path: ./src/main/resources
          action: sync
          target: /app/resources

    restart: unless-stopped