services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-spring-app:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: no
    develop:
      watch:
        - path: ./pom.xml
          action: rebuild

        - path: ./src
          action: rebuild

        - path: ./src/main/resources
          action: sync
          target: /app/resources
  nginx:
    image: nginx:alpine
    container_name: locus-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/locus.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - app
    restart: always
