spring.application.name=dockerSpring
spring.datasource.url=jdbc:postgresql://${RDS_HOST}:${RDS_PORT:5432}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
server.port=8080
#JWT Credentials
api.security.token.secret=${JWT_KEY}
api.jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
api.jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
api.jwt.issuer=${JWT_ISSUER}
#OAUTH2 Credentials
spring.security.oauth2.client.registration.google.client-id=${OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_SECRET_KEY}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
