spring.application.name=dockerSpring
spring.datasource.url=jdbc:postgresql://${RDS_HOST}:${RDS_PORT:5432}/${DB_NAME}?sslmode=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
server.port=8080
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
api.security.token.secret=${JWT_KEY}
api.jwt.access.expiration=${JWT_ACCESS_EXPIRATION}
api.jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION}
api.jwt.issuer=${JWT_ISSUER}

